### ISSUE TITLE
really love vakt! And it becomes an issue..

### ISSUE THREAD

**Issue by pyeprog** [kolotaev/vakt#16]
Vakt is really amzing! :cupid:

**Comment by kolotaev** [comment]
Hah, thank you!

@pyeprog, there is a 1.3 release upcoming with various caching mechanisms (useful if you have large policy sets) and a Policies YAML reader, with which you can define all your policies in YAML files in a declarative way.

**Comment by pyeprog** [comment]
can't wait !! :laughing:

**Comment by kolotaev** [comment]
I'm closing the issue with your permission.

Once again, thank you for such a feedback! It's really extremely pleasant to hear that you find vakt useful. :)
