### ISSUE TITLE
MongoDB reverse regex issue resolved

### ISSUE THREAD

**Issue by ketgo** [kolotaev/vakt#18]
The MongoDB reverse regex issue has been resolved in the 4.2 release. See https://jira.mongodb.org/browse/SERVER-11947

**Comment by kolotaev** [comment]
Ah, that's nice!

We need to add this functionality to MongoStorage. Note, that probably a migration will be needed in order to re-save existing policies in a way suitable for this type of filter.

**Comment by kolotaev** [comment]
@ketgo, do you want to take care of this? The reason I'm asking is because currently I don't have much spare time and if the feature is needed, I can't guarantee it will be done soon.

**Comment by ketgo** [comment]
Sure, I can start on it.

**Comment by kolotaev** [comment]
PR is here: https://github.com/kolotaev/vakt/pull/27
Is planned to be released as a part of 1.4.0 release train.

**Comment by kolotaev** [comment]
Resolved as of vakt v. 1.4.0.
