### ISSUE TITLE
Broken readme link

### ISSUE THREAD

**Issue by Skeen** [kolotaev/vakt#54]
The README contains this section:

> Description
>
> Vakt is an attribute-based and policy-based access control ([ABAC](https://en.wikipedia.org/wiki/Attribute-based_access_control)) toolkit that is based on policies. ABAC stands aside of RBAC and ACL models, giving you a fine-grained control on definition of the rules that restrict an access to resources and is generally considered a "next generation" authorization model. In its form Vakt resembles [IAM Policies](https://github.com/awsdocs/iam-user-guide/blob/master/doc_source/access_policies.md), but has a way nicer attribute managing.

However the link: https://github.com/awsdocs/iam-user-guide/blob/master/doc_source/access_policies.md is broken.

**Comment by kolotaev** [comment]
Hello! Thank you for noticing it. Fixed.
