### ISSUE TITLE
How to use ResourceIn

### ISSUE THREAD

**Issue by x0y-gt** [kolotaev/vakt#56]
Hi!
This is a question
It's being hard to understand ABAC for me, first time implementing it
I need help trying to create a policy to "Allow a store user to read the open orders of its store only", I have looked for tests or examples using ResourceIn, but just found a very simple rules test, so not sure how to use it, I have this

```python
policy = PolicyAllow(
    1,
    description="Allow a store owner to read orders only for their store",
    subjects=["manager"],
    resources=["order:<.+>"],
    actions=["read"],
    context={"store": ResourceIn()},
)

storage = MemoryStorage()
storage.add(policy)
guard = Guard(storage, RegexChecker())

i = Inquiry(
    subject="manager",
    resource="order:store1",
    action="read",
    context={"store": "order:store1"},
)

print(guard.is_allowed(i))  # False
```

How can I filter orders by some store ID and to check the open state of each order?

**Comment by kolotaev** [comment]
Hi 👋
In this example context in your Inquiry will be:

```diff
i = Inquiry(
    subject="manager",
    resource="order:store1",
    action="read",
-    context={"store": "order:store1"},
+    context={"store": ["order:store1"]},
)
```

Not sure if I should add `ResourceEqual` on par with `SubjectEqual` and `ActionEqual`. Probably yes. I'll think of it and if added, it will be available in the next release.

Thanks for the question!

**Comment by kolotaev** [comment]
Also, for your use-case the `ResourceMatch()` rule will also work out without changing Inquiry's context (`context={"store": "order:store1"}`).

**Comment by x0y-gt** [comment]
Thank you so much @kolotaev ! That did the job
