### ISSUE TITLE
Allow priority value for  policies

### ISSUE THREAD

**Issue by ketangoyal1988** [kolotaev/vakt#9]
In case of duplicated policies use a priority value to return the effect

**Comment by kolotaev** [comment]
Hi @ketangoyal1988,

Current implementation assumes [this](https://github.com/kolotaev/vakt/blob/master/vakt/guard.py#L70=L72) logic.
The reason behind it is motivated by the fact that it's always safe to be restrictive if there is an ambiguous situation.

2 absolutely identical policies (except for their IDs) will result in the same effect (according to their `effect` attribute value).
2 identical policies (except for their IDs and `effect`) will result in the most restrictive effect of both.

Could you please elaborate more on the issue: how can it be useful, why the current implementation is inconvenient/misleading, etc.

Thanks!

**Comment by ketangoyal1988** [comment]
Hi @kolotaev ,

After thinking over it, I believe the current logic would still work for my use case. However, adding a priority might be a nice to have feature. For example, in systems having role hierarchy, a priority assignment to the policy can be helpful. Taking a simple case of an organization having mangers and employees, a user with manager role will also have employee role. If the policy for employee is restrictive for a particular resource, while access is allowed for managers, as per the current implementation the manager would still be denied access.

Thanks for the quick reply!
